/********************************************************************************
** Form generated from reading UI file 'AntonovCNC.ui'
**
** Created by: Qt User Interface Compiler version 6.7.3
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_ANTONOVCNC_H
#define UI_ANTONOVCNC_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCommandLinkButton>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGraphicsView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QProgressBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_AntonovCNCClass
{
public:
    QWidget *centralWidget;
    QStackedWidget *stackedWidget;
    QWidget *page_3;
    QFrame *frame_4;
    QLabel *label_spindle_value;
    QLineEdit *label_spindle_speed;
    QSlider *slider_spindle_speed;
    QLineEdit *label_feed_rate;
    QSlider *slider_feed_rate;
    QLabel *label_feed_value;
    QFrame *frame_13;
    QLabel *info_line;
    QLabel *label_x_value_final;
    QFrame *frame_3;
    QListWidget *listWidget_program;
    QFrame *frame_5;
    QLabel *label_2;
    QFrame *frame_6;
    QFrame *frame_12;
    QCommandLinkButton *commandLinkButton_resetalarms;
    QCommandLinkButton *commandLinkButton_reset;
    QCommandLinkButton *commandLinkButton_start;
    QCommandLinkButton *commandLinkButton_stop;
    QLineEdit *lineEdit_4;
    QLineEdit *lineEdit_2;
    QLabel *label_z_value_final;
    QFrame *frame_2;
    QStackedWidget *stackedWidget_winchan;
    QWidget *page;
    QTextEdit *textEdit;
    QLabel *label_t_code_3;
    QLabel *label_g_code_20;
    QLabel *label_g_code_8;
    QLabel *label_d_code_4;
    QLabel *label_d_code_3;
    QLabel *label_g_code_13;
    QLabel *label_g_code_11;
    QLabel *label_g_code_27;
    QLabel *label_d_code;
    QLabel *label_m_code_4;
    QLabel *label_m_code_6;
    QLabel *label_g_code_10;
    QLabel *label_g_code_7;
    QLabel *label_g_code_16;
    QLabel *label_g_code_12;
    QLabel *label_g_code_26;
    QLabel *label_m_code_2;
    QLabel *label_g_code_6;
    QLabel *label_t_code_2;
    QLabel *label_g_code_21;
    QLabel *label_g_code_2;
    QLabel *label_m_code_5;
    QLabel *label_g_code_9;
    QLabel *label_g_code;
    QLabel *label_m_code;
    QLabel *label_m_code_3;
    QLabel *label_g_code_3;
    QLabel *label_g_code_15;
    QLabel *label_g_code_14;
    QLabel *label_g_code_22;
    QLabel *label_m_code_1;
    QLabel *label_g_code_23;
    QLabel *label_g_code_19;
    QLabel *label_d_code_2;
    QLabel *label_g_code_17;
    QLabel *label_g_code_4;
    QLabel *label_t_code_1;
    QLabel *label_g_code_24;
    QLabel *label_g_code_1;
    QLabel *label_g_code_29;
    QLabel *label_t_code;
    QLabel *label_g_code_25;
    QLabel *label_d_code_1;
    QLabel *label_t_code_6;
    QLabel *label_g_code_28;
    QLabel *label_t_code_4;
    QLabel *label_g_code_5;
    QLabel *label_g_code_18;
    QLabel *label_t_code_5;
    QWidget *page_2;
    QGraphicsView *graphView_simul;
    QLineEdit *label_x_axis;
    QLabel *label_x_value_current;
    QFrame *frame;
    QLineEdit *label_y_axis;
    QLineEdit *lineEdit_3;
    QFrame *frame_11;
    QFrame *frame_22;
    QPushButton *button_back;
    QFrame *frame_23;
    QPushButton *button_startkadr;
    QFrame *frame_24;
    QPushButton *button_korrekt;
    QFrame *frame_25;
    QPushButton *button_smesh;
    QFrame *frame_26;
    QPushButton *button_null3;
    QFrame *frame_27;
    QPushButton *button_null2;
    QFrame *frame_28;
    QPushButton *button_null1;
    QFrame *frame_29;
    QPushButton *button_selectprog;
    QFrame *frame_8;
    QLabel *label_y_value_final;
    QFrame *frame_10;
    QProgressBar *progressBar_runtime;
    QLabel *label_time;
    QLabel *label_date;
    QFrame *frame_14;
    QPushButton *button_numeration;
    QFrame *frame_15;
    QPushButton *button_smenaekrana;
    QFrame *frame_16;
    QPushButton *button_mmdyum;
    QFrame *frame_17;
    QPushButton *button_changesk;
    QFrame *frame_18;
    QPushButton *button_priv;
    QFrame *frame_19;
    QPushButton *button_ust0pos;
    QFrame *frame_20;
    QPushButton *button_privyazka;
    QFrame *frame_21;
    QPushButton *button_izmereniya;
    QLabel *label_y_value_current;
    QFrame *frame_9;
    QLabel *label_error;
    QFrame *frame_7;
    QLabel *label_chanel;
    QLabel *label_sostoyanine;
    QLabel *label_rejim_isp;
    QLineEdit *label_z_axis;
    QLabel *label_z_value_current;
    QFrame *frame_30;
    QLabel *label_language;
    QWidget *page_4;
    QProgressBar *progressBar_runtime_2;
    QLabel *label_time_2;
    QLabel *label_date_2;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *AntonovCNCClass)
    {
        if (AntonovCNCClass->objectName().isEmpty())
            AntonovCNCClass->setObjectName("AntonovCNCClass");
        AntonovCNCClass->resize(966, 865);
        AntonovCNCClass->setMinimumSize(QSize(966, 865));
        centralWidget = new QWidget(AntonovCNCClass);
        centralWidget->setObjectName("centralWidget");
        stackedWidget = new QStackedWidget(centralWidget);
        stackedWidget->setObjectName("stackedWidget");
        stackedWidget->setGeometry(QRect(0, 0, 961, 841));
        stackedWidget->setMinimumSize(QSize(0, 0));
        stackedWidget->setMaximumSize(QSize(966, 865));
        page_3 = new QWidget();
        page_3->setObjectName("page_3");
        frame_4 = new QFrame(page_3);
        frame_4->setObjectName("frame_4");
        frame_4->setGeometry(QRect(440, 560, 401, 141));
        frame_4->setFrameShape(QFrame::Shape::Box);
        frame_4->setFrameShadow(QFrame::Shadow::Plain);
        frame_4->setLineWidth(2);
        label_spindle_value = new QLabel(frame_4);
        label_spindle_value->setObjectName("label_spindle_value");
        label_spindle_value->setGeometry(QRect(230, 50, 141, 21));
        label_spindle_value->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_spindle_speed = new QLineEdit(frame_4);
        label_spindle_speed->setObjectName("label_spindle_speed");
        label_spindle_speed->setGeometry(QRect(232, 20, 141, 22));
        label_spindle_speed->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_spindle_speed->setReadOnly(true);
        slider_spindle_speed = new QSlider(frame_4);
        slider_spindle_speed->setObjectName("slider_spindle_speed");
        slider_spindle_speed->setGeometry(QRect(230, 80, 141, 22));
        slider_spindle_speed->setOrientation(Qt::Orientation::Horizontal);
        label_feed_rate = new QLineEdit(frame_4);
        label_feed_rate->setObjectName("label_feed_rate");
        label_feed_rate->setGeometry(QRect(20, 20, 141, 22));
        label_feed_rate->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_feed_rate->setReadOnly(true);
        slider_feed_rate = new QSlider(frame_4);
        slider_feed_rate->setObjectName("slider_feed_rate");
        slider_feed_rate->setGeometry(QRect(20, 80, 141, 22));
        slider_feed_rate->setOrientation(Qt::Orientation::Horizontal);
        label_feed_value = new QLabel(frame_4);
        label_feed_value->setObjectName("label_feed_value");
        label_feed_value->setGeometry(QRect(20, 50, 141, 21));
        label_feed_value->setAlignment(Qt::AlignmentFlag::AlignCenter);
        frame_13 = new QFrame(page_3);
        frame_13->setObjectName("frame_13");
        frame_13->setGeometry(QRect(440, 700, 301, 61));
        frame_13->setFrameShape(QFrame::Shape::Box);
        frame_13->setFrameShadow(QFrame::Shadow::Plain);
        frame_13->setLineWidth(2);
        info_line = new QLabel(frame_13);
        info_line->setObjectName("info_line");
        info_line->setGeometry(QRect(0, 0, 301, 61));
        info_line->setLineWidth(2);
        info_line->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_x_value_final = new QLabel(page_3);
        label_x_value_final->setObjectName("label_x_value_final");
        label_x_value_final->setGeometry(QRect(300, 160, 111, 21));
        label_x_value_final->setAlignment(Qt::AlignmentFlag::AlignCenter);
        frame_3 = new QFrame(page_3);
        frame_3->setObjectName("frame_3");
        frame_3->setGeometry(QRect(440, 110, 401, 451));
        frame_3->setFrameShape(QFrame::Shape::Box);
        frame_3->setFrameShadow(QFrame::Shadow::Plain);
        frame_3->setLineWidth(2);
        listWidget_program = new QListWidget(frame_3);
        listWidget_program->setObjectName("listWidget_program");
        listWidget_program->setGeometry(QRect(0, 0, 401, 451));
        frame_5 = new QFrame(page_3);
        frame_5->setObjectName("frame_5");
        frame_5->setGeometry(QRect(0, 0, 121, 61));
        frame_5->setFrameShape(QFrame::Shape::Box);
        frame_5->setFrameShadow(QFrame::Shadow::Plain);
        frame_5->setLineWidth(2);
        label_2 = new QLabel(frame_5);
        label_2->setObjectName("label_2");
        label_2->setGeometry(QRect(0, 0, 121, 61));
        label_2->setPixmap(QPixmap(QString::fromUtf8("../MAG_DEV_FILES/3.png")));
        frame_6 = new QFrame(frame_5);
        frame_6->setObjectName("frame_6");
        frame_6->setGeometry(QRect(0, 0, 121, 61));
        frame_6->setFrameShape(QFrame::Shape::Box);
        frame_6->setFrameShadow(QFrame::Shadow::Plain);
        frame_6->setLineWidth(2);
        frame_12 = new QFrame(page_3);
        frame_12->setObjectName("frame_12");
        frame_12->setGeometry(QRect(0, 640, 441, 121));
        frame_12->setFrameShape(QFrame::Shape::Box);
        frame_12->setFrameShadow(QFrame::Shadow::Plain);
        frame_12->setLineWidth(2);
        commandLinkButton_resetalarms = new QCommandLinkButton(frame_12);
        commandLinkButton_resetalarms->setObjectName("commandLinkButton_resetalarms");
        commandLinkButton_resetalarms->setGeometry(QRect(10, 10, 121, 41));
        QIcon icon(QIcon::fromTheme(QIcon::ThemeIcon::SystemReboot));
        commandLinkButton_resetalarms->setIcon(icon);
        commandLinkButton_resetalarms->setAutoDefault(false);
        commandLinkButton_reset = new QCommandLinkButton(frame_12);
        commandLinkButton_reset->setObjectName("commandLinkButton_reset");
        commandLinkButton_reset->setGeometry(QRect(10, 60, 101, 41));
        commandLinkButton_reset->setIcon(icon);
        commandLinkButton_reset->setAutoDefault(false);
        commandLinkButton_start = new QCommandLinkButton(frame_12);
        commandLinkButton_start->setObjectName("commandLinkButton_start");
        commandLinkButton_start->setGeometry(QRect(320, 10, 101, 41));
        QIcon icon1(QIcon::fromTheme(QIcon::ThemeIcon::MediaPlaybackStart));
        commandLinkButton_start->setIcon(icon1);
        commandLinkButton_stop = new QCommandLinkButton(frame_12);
        commandLinkButton_stop->setObjectName("commandLinkButton_stop");
        commandLinkButton_stop->setGeometry(QRect(320, 60, 101, 41));
        QIcon icon2(QIcon::fromTheme(QIcon::ThemeIcon::WindowClose));
        commandLinkButton_stop->setIcon(icon2);
        lineEdit_4 = new QLineEdit(page_3);
        lineEdit_4->setObjectName("lineEdit_4");
        lineEdit_4->setGeometry(QRect(160, 120, 113, 22));
        lineEdit_4->setAlignment(Qt::AlignmentFlag::AlignCenter);
        lineEdit_4->setReadOnly(true);
        lineEdit_2 = new QLineEdit(page_3);
        lineEdit_2->setObjectName("lineEdit_2");
        lineEdit_2->setGeometry(QRect(20, 120, 113, 22));
        lineEdit_2->setAlignment(Qt::AlignmentFlag::AlignCenter);
        lineEdit_2->setReadOnly(true);
        label_z_value_final = new QLabel(page_3);
        label_z_value_final->setObjectName("label_z_value_final");
        label_z_value_final->setGeometry(QRect(300, 220, 111, 21));
        label_z_value_final->setAlignment(Qt::AlignmentFlag::AlignCenter);
        frame_2 = new QFrame(page_3);
        frame_2->setObjectName("frame_2");
        frame_2->setGeometry(QRect(0, 270, 441, 371));
        frame_2->setFrameShape(QFrame::Shape::Box);
        frame_2->setFrameShadow(QFrame::Shadow::Plain);
        frame_2->setLineWidth(2);
        stackedWidget_winchan = new QStackedWidget(frame_2);
        stackedWidget_winchan->setObjectName("stackedWidget_winchan");
        stackedWidget_winchan->setGeometry(QRect(10, 10, 411, 351));
        page = new QWidget();
        page->setObjectName("page");
        textEdit = new QTextEdit(page);
        textEdit->setObjectName("textEdit");
        textEdit->setGeometry(QRect(0, 20, 411, 31));
        textEdit->setReadOnly(true);
        label_t_code_3 = new QLabel(page);
        label_t_code_3->setObjectName("label_t_code_3");
        label_t_code_3->setGeometry(QRect(370, 160, 41, 31));
        label_t_code_3->setFrameShape(QFrame::Shape::Box);
        label_t_code_3->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_20 = new QLabel(page);
        label_g_code_20->setObjectName("label_g_code_20");
        label_g_code_20->setGeometry(QRect(0, 250, 41, 31));
        label_g_code_20->setFrameShape(QFrame::Shape::Box);
        label_g_code_20->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_8 = new QLabel(page);
        label_g_code_8->setObjectName("label_g_code_8");
        label_g_code_8->setGeometry(QRect(200, 160, 41, 31));
        label_g_code_8->setFrameShape(QFrame::Shape::Box);
        label_g_code_8->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_d_code_4 = new QLabel(page);
        label_d_code_4->setObjectName("label_d_code_4");
        label_d_code_4->setGeometry(QRect(330, 220, 41, 31));
        label_d_code_4->setFrameShape(QFrame::Shape::Box);
        label_d_code_4->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_d_code_3 = new QLabel(page);
        label_d_code_3->setObjectName("label_d_code_3");
        label_d_code_3->setGeometry(QRect(330, 190, 41, 31));
        label_d_code_3->setFrameShape(QFrame::Shape::Box);
        label_d_code_3->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_13 = new QLabel(page);
        label_g_code_13->setObjectName("label_g_code_13");
        label_g_code_13->setGeometry(QRect(160, 190, 41, 31));
        label_g_code_13->setFrameShape(QFrame::Shape::Box);
        label_g_code_13->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_11 = new QLabel(page);
        label_g_code_11->setObjectName("label_g_code_11");
        label_g_code_11->setGeometry(QRect(80, 190, 41, 31));
        label_g_code_11->setFrameShape(QFrame::Shape::Box);
        label_g_code_11->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_27 = new QLabel(page);
        label_g_code_27->setObjectName("label_g_code_27");
        label_g_code_27->setGeometry(QRect(80, 280, 41, 31));
        label_g_code_27->setFrameShape(QFrame::Shape::Box);
        label_g_code_27->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_d_code = new QLabel(page);
        label_d_code->setObjectName("label_d_code");
        label_d_code->setGeometry(QRect(200, 80, 41, 31));
        label_d_code->setFrameShape(QFrame::Shape::Box);
        label_d_code->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_m_code_4 = new QLabel(page);
        label_m_code_4->setObjectName("label_m_code_4");
        label_m_code_4->setGeometry(QRect(290, 190, 41, 31));
        label_m_code_4->setFrameShape(QFrame::Shape::Box);
        label_m_code_4->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_m_code_6 = new QLabel(page);
        label_m_code_6->setObjectName("label_m_code_6");
        label_m_code_6->setGeometry(QRect(290, 250, 41, 31));
        label_m_code_6->setFrameShape(QFrame::Shape::Box);
        label_m_code_6->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_10 = new QLabel(page);
        label_g_code_10->setObjectName("label_g_code_10");
        label_g_code_10->setGeometry(QRect(40, 190, 41, 31));
        label_g_code_10->setFrameShape(QFrame::Shape::Box);
        label_g_code_10->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_7 = new QLabel(page);
        label_g_code_7->setObjectName("label_g_code_7");
        label_g_code_7->setGeometry(QRect(160, 160, 41, 31));
        label_g_code_7->setFrameShape(QFrame::Shape::Box);
        label_g_code_7->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_16 = new QLabel(page);
        label_g_code_16->setObjectName("label_g_code_16");
        label_g_code_16->setGeometry(QRect(160, 220, 41, 31));
        label_g_code_16->setFrameShape(QFrame::Shape::Box);
        label_g_code_16->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_12 = new QLabel(page);
        label_g_code_12->setObjectName("label_g_code_12");
        label_g_code_12->setGeometry(QRect(120, 190, 41, 31));
        label_g_code_12->setFrameShape(QFrame::Shape::Box);
        label_g_code_12->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_26 = new QLabel(page);
        label_g_code_26->setObjectName("label_g_code_26");
        label_g_code_26->setGeometry(QRect(40, 280, 41, 31));
        label_g_code_26->setFrameShape(QFrame::Shape::Box);
        label_g_code_26->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_m_code_2 = new QLabel(page);
        label_m_code_2->setObjectName("label_m_code_2");
        label_m_code_2->setGeometry(QRect(290, 280, 41, 31));
        label_m_code_2->setFrameShape(QFrame::Shape::Box);
        label_m_code_2->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_6 = new QLabel(page);
        label_g_code_6->setObjectName("label_g_code_6");
        label_g_code_6->setGeometry(QRect(120, 160, 41, 31));
        label_g_code_6->setFrameShape(QFrame::Shape::Box);
        label_g_code_6->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_t_code_2 = new QLabel(page);
        label_t_code_2->setObjectName("label_t_code_2");
        label_t_code_2->setGeometry(QRect(160, 80, 41, 31));
        label_t_code_2->setFrameShape(QFrame::Shape::Box);
        label_t_code_2->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_21 = new QLabel(page);
        label_g_code_21->setObjectName("label_g_code_21");
        label_g_code_21->setGeometry(QRect(40, 250, 41, 31));
        label_g_code_21->setFrameShape(QFrame::Shape::Box);
        label_g_code_21->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_2 = new QLabel(page);
        label_g_code_2->setObjectName("label_g_code_2");
        label_g_code_2->setGeometry(QRect(120, 220, 41, 31));
        label_g_code_2->setFrameShape(QFrame::Shape::Box);
        label_g_code_2->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_m_code_5 = new QLabel(page);
        label_m_code_5->setObjectName("label_m_code_5");
        label_m_code_5->setGeometry(QRect(290, 220, 41, 31));
        label_m_code_5->setFrameShape(QFrame::Shape::Box);
        label_m_code_5->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_9 = new QLabel(page);
        label_g_code_9->setObjectName("label_g_code_9");
        label_g_code_9->setGeometry(QRect(0, 190, 41, 31));
        label_g_code_9->setFrameShape(QFrame::Shape::Box);
        label_g_code_9->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code = new QLabel(page);
        label_g_code->setObjectName("label_g_code");
        label_g_code->setGeometry(QRect(200, 280, 41, 31));
        label_g_code->setFrameShape(QFrame::Shape::Box);
        label_g_code->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_m_code = new QLabel(page);
        label_m_code->setObjectName("label_m_code");
        label_m_code->setGeometry(QRect(290, 160, 41, 31));
        label_m_code->setFrameShape(QFrame::Shape::Box);
        label_m_code->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_m_code_3 = new QLabel(page);
        label_m_code_3->setObjectName("label_m_code_3");
        label_m_code_3->setGeometry(QRect(330, 250, 41, 31));
        label_m_code_3->setFrameShape(QFrame::Shape::Box);
        label_m_code_3->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_3 = new QLabel(page);
        label_g_code_3->setObjectName("label_g_code_3");
        label_g_code_3->setGeometry(QRect(0, 160, 41, 31));
        label_g_code_3->setFrameShape(QFrame::Shape::Box);
        label_g_code_3->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_15 = new QLabel(page);
        label_g_code_15->setObjectName("label_g_code_15");
        label_g_code_15->setGeometry(QRect(200, 220, 41, 31));
        label_g_code_15->setFrameShape(QFrame::Shape::Box);
        label_g_code_15->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_14 = new QLabel(page);
        label_g_code_14->setObjectName("label_g_code_14");
        label_g_code_14->setGeometry(QRect(200, 190, 41, 31));
        label_g_code_14->setFrameShape(QFrame::Shape::Box);
        label_g_code_14->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_22 = new QLabel(page);
        label_g_code_22->setObjectName("label_g_code_22");
        label_g_code_22->setGeometry(QRect(80, 250, 41, 31));
        label_g_code_22->setFrameShape(QFrame::Shape::Box);
        label_g_code_22->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_m_code_1 = new QLabel(page);
        label_m_code_1->setObjectName("label_m_code_1");
        label_m_code_1->setGeometry(QRect(330, 280, 41, 31));
        label_m_code_1->setFrameShape(QFrame::Shape::Box);
        label_m_code_1->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_23 = new QLabel(page);
        label_g_code_23->setObjectName("label_g_code_23");
        label_g_code_23->setGeometry(QRect(160, 250, 41, 31));
        label_g_code_23->setFrameShape(QFrame::Shape::Box);
        label_g_code_23->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_19 = new QLabel(page);
        label_g_code_19->setObjectName("label_g_code_19");
        label_g_code_19->setGeometry(QRect(0, 220, 41, 31));
        label_g_code_19->setFrameShape(QFrame::Shape::Box);
        label_g_code_19->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_d_code_2 = new QLabel(page);
        label_d_code_2->setObjectName("label_d_code_2");
        label_d_code_2->setGeometry(QRect(40, 80, 41, 31));
        label_d_code_2->setFrameShape(QFrame::Shape::Box);
        label_d_code_2->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_17 = new QLabel(page);
        label_g_code_17->setObjectName("label_g_code_17");
        label_g_code_17->setGeometry(QRect(80, 220, 41, 31));
        label_g_code_17->setFrameShape(QFrame::Shape::Box);
        label_g_code_17->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_4 = new QLabel(page);
        label_g_code_4->setObjectName("label_g_code_4");
        label_g_code_4->setGeometry(QRect(40, 160, 41, 31));
        label_g_code_4->setFrameShape(QFrame::Shape::Box);
        label_g_code_4->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_t_code_1 = new QLabel(page);
        label_t_code_1->setObjectName("label_t_code_1");
        label_t_code_1->setGeometry(QRect(370, 280, 41, 31));
        label_t_code_1->setFrameShape(QFrame::Shape::Box);
        label_t_code_1->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_24 = new QLabel(page);
        label_g_code_24->setObjectName("label_g_code_24");
        label_g_code_24->setGeometry(QRect(200, 250, 41, 31));
        label_g_code_24->setFrameShape(QFrame::Shape::Box);
        label_g_code_24->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_1 = new QLabel(page);
        label_g_code_1->setObjectName("label_g_code_1");
        label_g_code_1->setGeometry(QRect(120, 250, 41, 31));
        label_g_code_1->setFrameShape(QFrame::Shape::Box);
        label_g_code_1->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_29 = new QLabel(page);
        label_g_code_29->setObjectName("label_g_code_29");
        label_g_code_29->setGeometry(QRect(160, 280, 41, 31));
        label_g_code_29->setFrameShape(QFrame::Shape::Box);
        label_g_code_29->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_t_code = new QLabel(page);
        label_t_code->setObjectName("label_t_code");
        label_t_code->setGeometry(QRect(0, 80, 41, 31));
        label_t_code->setFrameShape(QFrame::Shape::Box);
        label_t_code->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_25 = new QLabel(page);
        label_g_code_25->setObjectName("label_g_code_25");
        label_g_code_25->setGeometry(QRect(0, 280, 41, 31));
        label_g_code_25->setFrameShape(QFrame::Shape::Box);
        label_g_code_25->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_d_code_1 = new QLabel(page);
        label_d_code_1->setObjectName("label_d_code_1");
        label_d_code_1->setGeometry(QRect(330, 160, 41, 31));
        label_d_code_1->setFrameShape(QFrame::Shape::Box);
        label_d_code_1->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_t_code_6 = new QLabel(page);
        label_t_code_6->setObjectName("label_t_code_6");
        label_t_code_6->setGeometry(QRect(370, 250, 41, 31));
        label_t_code_6->setFrameShape(QFrame::Shape::Box);
        label_t_code_6->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_28 = new QLabel(page);
        label_g_code_28->setObjectName("label_g_code_28");
        label_g_code_28->setGeometry(QRect(120, 280, 41, 31));
        label_g_code_28->setFrameShape(QFrame::Shape::Box);
        label_g_code_28->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_t_code_4 = new QLabel(page);
        label_t_code_4->setObjectName("label_t_code_4");
        label_t_code_4->setGeometry(QRect(370, 190, 41, 31));
        label_t_code_4->setFrameShape(QFrame::Shape::Box);
        label_t_code_4->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_5 = new QLabel(page);
        label_g_code_5->setObjectName("label_g_code_5");
        label_g_code_5->setGeometry(QRect(80, 160, 41, 31));
        label_g_code_5->setFrameShape(QFrame::Shape::Box);
        label_g_code_5->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_18 = new QLabel(page);
        label_g_code_18->setObjectName("label_g_code_18");
        label_g_code_18->setGeometry(QRect(40, 220, 41, 31));
        label_g_code_18->setFrameShape(QFrame::Shape::Box);
        label_g_code_18->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_t_code_5 = new QLabel(page);
        label_t_code_5->setObjectName("label_t_code_5");
        label_t_code_5->setGeometry(QRect(370, 220, 41, 31));
        label_t_code_5->setFrameShape(QFrame::Shape::Box);
        label_t_code_5->setAlignment(Qt::AlignmentFlag::AlignCenter);
        stackedWidget_winchan->addWidget(page);
        page_2 = new QWidget();
        page_2->setObjectName("page_2");
        graphView_simul = new QGraphicsView(page_2);
        graphView_simul->setObjectName("graphView_simul");
        graphView_simul->setGeometry(QRect(0, 0, 411, 351));
        stackedWidget_winchan->addWidget(page_2);
        label_x_axis = new QLineEdit(page_3);
        label_x_axis->setObjectName("label_x_axis");
        label_x_axis->setGeometry(QRect(20, 160, 113, 22));
        label_x_axis->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_x_axis->setReadOnly(true);
        label_x_value_current = new QLabel(page_3);
        label_x_value_current->setObjectName("label_x_value_current");
        label_x_value_current->setGeometry(QRect(160, 160, 111, 21));
        label_x_value_current->setAlignment(Qt::AlignmentFlag::AlignCenter);
        frame = new QFrame(page_3);
        frame->setObjectName("frame");
        frame->setGeometry(QRect(0, 110, 441, 161));
        frame->setFrameShape(QFrame::Shape::Box);
        frame->setFrameShadow(QFrame::Shadow::Plain);
        frame->setLineWidth(2);
        label_y_axis = new QLineEdit(page_3);
        label_y_axis->setObjectName("label_y_axis");
        label_y_axis->setGeometry(QRect(20, 190, 113, 22));
        label_y_axis->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_y_axis->setReadOnly(true);
        lineEdit_3 = new QLineEdit(page_3);
        lineEdit_3->setObjectName("lineEdit_3");
        lineEdit_3->setGeometry(QRect(300, 120, 113, 22));
        lineEdit_3->setAlignment(Qt::AlignmentFlag::AlignCenter);
        lineEdit_3->setReadOnly(true);
        frame_11 = new QFrame(page_3);
        frame_11->setObjectName("frame_11");
        frame_11->setGeometry(QRect(0, 760, 961, 81));
        frame_11->setFrameShape(QFrame::Shape::Box);
        frame_11->setFrameShadow(QFrame::Shadow::Plain);
        frame_22 = new QFrame(frame_11);
        frame_22->setObjectName("frame_22");
        frame_22->setGeometry(QRect(840, 0, 121, 81));
        frame_22->setFrameShape(QFrame::Shape::Box);
        frame_22->setFrameShadow(QFrame::Shadow::Plain);
        button_back = new QPushButton(frame_22);
        button_back->setObjectName("button_back");
        button_back->setGeometry(QRect(0, 0, 121, 81));
        frame_23 = new QFrame(frame_11);
        frame_23->setObjectName("frame_23");
        frame_23->setGeometry(QRect(720, 0, 121, 81));
        frame_23->setFrameShape(QFrame::Shape::Box);
        frame_23->setFrameShadow(QFrame::Shadow::Plain);
        button_startkadr = new QPushButton(frame_23);
        button_startkadr->setObjectName("button_startkadr");
        button_startkadr->setGeometry(QRect(0, 0, 121, 81));
        frame_24 = new QFrame(frame_11);
        frame_24->setObjectName("frame_24");
        frame_24->setGeometry(QRect(600, 0, 121, 81));
        frame_24->setFrameShape(QFrame::Shape::Box);
        frame_24->setFrameShadow(QFrame::Shadow::Plain);
        button_korrekt = new QPushButton(frame_24);
        button_korrekt->setObjectName("button_korrekt");
        button_korrekt->setGeometry(QRect(0, 0, 121, 81));
        frame_25 = new QFrame(frame_11);
        frame_25->setObjectName("frame_25");
        frame_25->setGeometry(QRect(480, 0, 121, 81));
        frame_25->setFrameShape(QFrame::Shape::Box);
        frame_25->setFrameShadow(QFrame::Shadow::Plain);
        button_smesh = new QPushButton(frame_25);
        button_smesh->setObjectName("button_smesh");
        button_smesh->setGeometry(QRect(0, 0, 121, 81));
        frame_26 = new QFrame(frame_11);
        frame_26->setObjectName("frame_26");
        frame_26->setGeometry(QRect(360, 0, 121, 81));
        frame_26->setFrameShape(QFrame::Shape::Box);
        frame_26->setFrameShadow(QFrame::Shadow::Plain);
        button_null3 = new QPushButton(frame_26);
        button_null3->setObjectName("button_null3");
        button_null3->setGeometry(QRect(0, 0, 121, 81));
        frame_27 = new QFrame(frame_11);
        frame_27->setObjectName("frame_27");
        frame_27->setGeometry(QRect(240, 0, 121, 81));
        frame_27->setFrameShape(QFrame::Shape::Box);
        frame_27->setFrameShadow(QFrame::Shadow::Plain);
        button_null2 = new QPushButton(frame_27);
        button_null2->setObjectName("button_null2");
        button_null2->setGeometry(QRect(0, 0, 121, 81));
        frame_28 = new QFrame(frame_11);
        frame_28->setObjectName("frame_28");
        frame_28->setGeometry(QRect(120, 0, 121, 81));
        frame_28->setFrameShape(QFrame::Shape::Box);
        frame_28->setFrameShadow(QFrame::Shadow::Plain);
        button_null1 = new QPushButton(frame_28);
        button_null1->setObjectName("button_null1");
        button_null1->setGeometry(QRect(0, 0, 121, 81));
        frame_29 = new QFrame(frame_11);
        frame_29->setObjectName("frame_29");
        frame_29->setGeometry(QRect(0, 0, 121, 81));
        frame_29->setFrameShape(QFrame::Shape::Box);
        frame_29->setFrameShadow(QFrame::Shadow::Plain);
        button_selectprog = new QPushButton(frame_29);
        button_selectprog->setObjectName("button_selectprog");
        button_selectprog->setGeometry(QRect(0, 0, 121, 81));
        frame_8 = new QFrame(page_3);
        frame_8->setObjectName("frame_8");
        frame_8->setGeometry(QRect(650, 0, 191, 61));
        frame_8->setFrameShape(QFrame::Shape::Box);
        frame_8->setFrameShadow(QFrame::Shadow::Plain);
        frame_8->setLineWidth(2);
        label_y_value_final = new QLabel(page_3);
        label_y_value_final->setObjectName("label_y_value_final");
        label_y_value_final->setGeometry(QRect(300, 190, 111, 21));
        label_y_value_final->setAlignment(Qt::AlignmentFlag::AlignCenter);
        frame_10 = new QFrame(page_3);
        frame_10->setObjectName("frame_10");
        frame_10->setGeometry(QRect(840, 0, 121, 761));
        frame_10->setFrameShape(QFrame::Shape::Box);
        frame_10->setFrameShadow(QFrame::Shadow::Plain);
        frame_10->setLineWidth(2);
        progressBar_runtime = new QProgressBar(frame_10);
        progressBar_runtime->setObjectName("progressBar_runtime");
        progressBar_runtime->setGeometry(QRect(10, 80, 99, 24));
        progressBar_runtime->setValue(0);
        progressBar_runtime->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_time = new QLabel(frame_10);
        label_time->setObjectName("label_time");
        label_time->setGeometry(QRect(10, 40, 99, 29));
        QFont font;
        font.setFamilies({QString::fromUtf8("Times New Roman")});
        font.setPointSize(11);
        font.setBold(true);
        label_time->setFont(font);
        label_time->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_date = new QLabel(frame_10);
        label_date->setObjectName("label_date");
        label_date->setGeometry(QRect(10, 10, 99, 29));
        label_date->setFont(font);
        label_date->setAlignment(Qt::AlignmentFlag::AlignCenter);
        frame_14 = new QFrame(frame_10);
        frame_14->setObjectName("frame_14");
        frame_14->setGeometry(QRect(0, 120, 121, 81));
        frame_14->setFrameShape(QFrame::Shape::Box);
        frame_14->setFrameShadow(QFrame::Shadow::Plain);
        button_numeration = new QPushButton(frame_14);
        button_numeration->setObjectName("button_numeration");
        button_numeration->setGeometry(QRect(0, 0, 121, 81));
        frame_15 = new QFrame(frame_10);
        frame_15->setObjectName("frame_15");
        frame_15->setGeometry(QRect(0, 200, 121, 81));
        frame_15->setFrameShape(QFrame::Shape::Box);
        frame_15->setFrameShadow(QFrame::Shadow::Plain);
        button_smenaekrana = new QPushButton(frame_15);
        button_smenaekrana->setObjectName("button_smenaekrana");
        button_smenaekrana->setGeometry(QRect(0, 0, 121, 81));
        frame_16 = new QFrame(frame_10);
        frame_16->setObjectName("frame_16");
        frame_16->setGeometry(QRect(0, 280, 121, 81));
        frame_16->setFrameShape(QFrame::Shape::Box);
        frame_16->setFrameShadow(QFrame::Shadow::Plain);
        button_mmdyum = new QPushButton(frame_16);
        button_mmdyum->setObjectName("button_mmdyum");
        button_mmdyum->setGeometry(QRect(0, 0, 121, 81));
        frame_17 = new QFrame(frame_10);
        frame_17->setObjectName("frame_17");
        frame_17->setGeometry(QRect(0, 360, 121, 81));
        frame_17->setFrameShape(QFrame::Shape::Box);
        frame_17->setFrameShadow(QFrame::Shadow::Plain);
        button_changesk = new QPushButton(frame_17);
        button_changesk->setObjectName("button_changesk");
        button_changesk->setGeometry(QRect(0, 0, 121, 81));
        frame_18 = new QFrame(frame_10);
        frame_18->setObjectName("frame_18");
        frame_18->setGeometry(QRect(0, 440, 121, 81));
        frame_18->setFrameShape(QFrame::Shape::Box);
        frame_18->setFrameShadow(QFrame::Shadow::Plain);
        button_priv = new QPushButton(frame_18);
        button_priv->setObjectName("button_priv");
        button_priv->setGeometry(QRect(0, 0, 121, 81));
        frame_19 = new QFrame(frame_10);
        frame_19->setObjectName("frame_19");
        frame_19->setGeometry(QRect(0, 520, 121, 81));
        frame_19->setFrameShape(QFrame::Shape::Box);
        frame_19->setFrameShadow(QFrame::Shadow::Plain);
        button_ust0pos = new QPushButton(frame_19);
        button_ust0pos->setObjectName("button_ust0pos");
        button_ust0pos->setGeometry(QRect(0, 0, 121, 81));
        frame_20 = new QFrame(frame_10);
        frame_20->setObjectName("frame_20");
        frame_20->setGeometry(QRect(0, 600, 121, 81));
        frame_20->setFrameShape(QFrame::Shape::Box);
        frame_20->setFrameShadow(QFrame::Shadow::Plain);
        button_privyazka = new QPushButton(frame_20);
        button_privyazka->setObjectName("button_privyazka");
        button_privyazka->setGeometry(QRect(0, 0, 121, 81));
        frame_21 = new QFrame(frame_10);
        frame_21->setObjectName("frame_21");
        frame_21->setGeometry(QRect(0, 680, 121, 81));
        frame_21->setFrameShape(QFrame::Shape::Box);
        frame_21->setFrameShadow(QFrame::Shadow::Plain);
        button_izmereniya = new QPushButton(frame_21);
        button_izmereniya->setObjectName("button_izmereniya");
        button_izmereniya->setGeometry(QRect(0, 0, 121, 81));
        label_y_value_current = new QLabel(page_3);
        label_y_value_current->setObjectName("label_y_value_current");
        label_y_value_current->setGeometry(QRect(160, 190, 111, 21));
        label_y_value_current->setAlignment(Qt::AlignmentFlag::AlignCenter);
        frame_9 = new QFrame(page_3);
        frame_9->setObjectName("frame_9");
        frame_9->setGeometry(QRect(0, 60, 841, 51));
        frame_9->setFrameShape(QFrame::Shape::Box);
        frame_9->setFrameShadow(QFrame::Shadow::Plain);
        frame_9->setLineWidth(2);
        label_error = new QLabel(frame_9);
        label_error->setObjectName("label_error");
        label_error->setGeometry(QRect(30, 0, 801, 51));
        label_error->setAlignment(Qt::AlignmentFlag::AlignCenter);
        frame_7 = new QFrame(page_3);
        frame_7->setObjectName("frame_7");
        frame_7->setGeometry(QRect(120, 0, 531, 61));
        frame_7->setFrameShape(QFrame::Shape::Box);
        frame_7->setFrameShadow(QFrame::Shadow::Plain);
        frame_7->setLineWidth(2);
        label_chanel = new QLabel(frame_7);
        label_chanel->setObjectName("label_chanel");
        label_chanel->setGeometry(QRect(380, 10, 81, 41));
        label_chanel->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_sostoyanine = new QLabel(frame_7);
        label_sostoyanine->setObjectName("label_sostoyanine");
        label_sostoyanine->setGeometry(QRect(180, 10, 121, 41));
        label_sostoyanine->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_rejim_isp = new QLabel(frame_7);
        label_rejim_isp->setObjectName("label_rejim_isp");
        label_rejim_isp->setGeometry(QRect(40, 10, 81, 41));
        label_rejim_isp->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_z_axis = new QLineEdit(page_3);
        label_z_axis->setObjectName("label_z_axis");
        label_z_axis->setGeometry(QRect(20, 220, 113, 22));
        label_z_axis->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_z_axis->setReadOnly(true);
        label_z_value_current = new QLabel(page_3);
        label_z_value_current->setObjectName("label_z_value_current");
        label_z_value_current->setGeometry(QRect(160, 220, 111, 21));
        label_z_value_current->setAlignment(Qt::AlignmentFlag::AlignCenter);
        frame_30 = new QFrame(page_3);
        frame_30->setObjectName("frame_30");
        frame_30->setGeometry(QRect(740, 700, 101, 61));
        frame_30->setFrameShape(QFrame::Shape::Box);
        frame_30->setFrameShadow(QFrame::Shadow::Plain);
        frame_30->setLineWidth(2);
        label_language = new QLabel(frame_30);
        label_language->setObjectName("label_language");
        label_language->setGeometry(QRect(10, 10, 81, 41));
        label_language->setAlignment(Qt::AlignmentFlag::AlignCenter);
        stackedWidget->addWidget(page_3);
        page_4 = new QWidget();
        page_4->setObjectName("page_4");
        progressBar_runtime_2 = new QProgressBar(page_4);
        progressBar_runtime_2->setObjectName("progressBar_runtime_2");
        progressBar_runtime_2->setGeometry(QRect(850, 80, 99, 24));
        progressBar_runtime_2->setValue(0);
        progressBar_runtime_2->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_time_2 = new QLabel(page_4);
        label_time_2->setObjectName("label_time_2");
        label_time_2->setGeometry(QRect(850, 40, 99, 29));
        label_time_2->setFont(font);
        label_time_2->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_date_2 = new QLabel(page_4);
        label_date_2->setObjectName("label_date_2");
        label_date_2->setGeometry(QRect(850, 10, 99, 29));
        label_date_2->setFont(font);
        label_date_2->setAlignment(Qt::AlignmentFlag::AlignCenter);
        stackedWidget->addWidget(page_4);
        AntonovCNCClass->setCentralWidget(centralWidget);
        statusBar = new QStatusBar(AntonovCNCClass);
        statusBar->setObjectName("statusBar");
        AntonovCNCClass->setStatusBar(statusBar);

        retranslateUi(AntonovCNCClass);

        stackedWidget->setCurrentIndex(0);
        stackedWidget_winchan->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(AntonovCNCClass);
    } // setupUi

    void retranslateUi(QMainWindow *AntonovCNCClass)
    {
        AntonovCNCClass->setWindowTitle(QCoreApplication::translate("AntonovCNCClass", "AntonovCNC", nullptr));
        label_spindle_value->setText(QCoreApplication::translate("AntonovCNCClass", "0", nullptr));
        label_spindle_speed->setText(QCoreApplication::translate("AntonovCNCClass", "\320\236\320\261\320\276\321\200\320\276\321\202\321\213", nullptr));
        label_feed_rate->setText(QCoreApplication::translate("AntonovCNCClass", "\320\237\320\276\320\264\320\260\321\207\320\260", nullptr));
        label_feed_value->setText(QCoreApplication::translate("AntonovCNCClass", "0", nullptr));
        info_line->setText(QCoreApplication::translate("AntonovCNCClass", "\320\241\321\202\321\200\320\276\320\272\320\260 \320\270\320\275\321\204\320\276\321\200\320\274\320\260\321\206\320\270\320\270", nullptr));
        label_x_value_final->setText(QCoreApplication::translate("AntonovCNCClass", "x_00", nullptr));
        label_2->setText(QString());
        commandLinkButton_resetalarms->setText(QCoreApplication::translate("AntonovCNCClass", "Reset Alarm", nullptr));
        commandLinkButton_reset->setText(QCoreApplication::translate("AntonovCNCClass", "Reset", nullptr));
        commandLinkButton_start->setText(QCoreApplication::translate("AntonovCNCClass", "Start", nullptr));
        commandLinkButton_stop->setText(QCoreApplication::translate("AntonovCNCClass", "Stop", nullptr));
        lineEdit_4->setText(QCoreApplication::translate("AntonovCNCClass", "\320\242\320\265\320\272\321\203\321\211\320\260\321\217", nullptr));
        lineEdit_2->setText(QCoreApplication::translate("AntonovCNCClass", "\320\241\320\232\320\241", nullptr));
        label_z_value_final->setText(QCoreApplication::translate("AntonovCNCClass", "z_00", nullptr));
        textEdit->setHtml(QCoreApplication::translate("AntonovCNCClass", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">\320\220\320\272\321\202\320\270\320\262\320\275\321\213\320\265 \321\204\321\203\320\275\320\272\321\206\320\270\320\270</span></p></body></html>", nullptr));
        label_t_code_3->setText(QString());
        label_g_code_20->setText(QString());
        label_g_code_8->setText(QString());
        label_d_code_4->setText(QString());
        label_d_code_3->setText(QString());
        label_g_code_13->setText(QString());
        label_g_code_11->setText(QString());
        label_g_code_27->setText(QString());
        label_d_code->setText(QString());
        label_m_code_4->setText(QString());
        label_m_code_6->setText(QString());
        label_g_code_10->setText(QString());
        label_g_code_7->setText(QString());
        label_g_code_16->setText(QString());
        label_g_code_12->setText(QString());
        label_g_code_26->setText(QString());
        label_m_code_2->setText(QString());
        label_g_code_6->setText(QString());
        label_t_code_2->setText(QString());
        label_g_code_21->setText(QString());
        label_g_code_2->setText(QString());
        label_m_code_5->setText(QString());
        label_g_code_9->setText(QString());
        label_g_code->setText(QString());
        label_m_code->setText(QString());
        label_m_code_3->setText(QString());
        label_g_code_3->setText(QString());
        label_g_code_15->setText(QString());
        label_g_code_14->setText(QString());
        label_g_code_22->setText(QString());
        label_m_code_1->setText(QString());
        label_g_code_23->setText(QString());
        label_g_code_19->setText(QString());
        label_d_code_2->setText(QString());
        label_g_code_17->setText(QString());
        label_g_code_4->setText(QString());
        label_t_code_1->setText(QString());
        label_g_code_24->setText(QString());
        label_g_code_1->setText(QString());
        label_g_code_29->setText(QString());
        label_t_code->setText(QString());
        label_g_code_25->setText(QString());
        label_d_code_1->setText(QString());
        label_t_code_6->setText(QString());
        label_g_code_28->setText(QString());
        label_t_code_4->setText(QString());
        label_g_code_5->setText(QString());
        label_g_code_18->setText(QString());
        label_t_code_5->setText(QString());
        label_x_axis->setText(QCoreApplication::translate("AntonovCNCClass", "X", nullptr));
        label_x_value_current->setText(QCoreApplication::translate("AntonovCNCClass", "x_0", nullptr));
        label_y_axis->setText(QCoreApplication::translate("AntonovCNCClass", "Y", nullptr));
        lineEdit_3->setText(QCoreApplication::translate("AntonovCNCClass", "\320\232\320\276\320\275\320\265\321\207\320\275\320\260\321\217", nullptr));
        button_back->setText(QCoreApplication::translate("AntonovCNCClass", "\320\222\320\276\320\267\320\262\321\200\320\260\321\202", nullptr));
        button_startkadr->setText(QCoreApplication::translate("AntonovCNCClass", "\320\227\320\260\320\277\321\203\321\201\320\272 \321\201 \n"
"\320\262\321\213\320\261\321\200\320\260\320\275\320\275\320\276\320\263\320\276 \n"
"\320\272\320\260\320\264\321\200\320\260", nullptr));
        button_korrekt->setText(QCoreApplication::translate("AntonovCNCClass", "\320\232\320\276\321\200\321\200\320\265\320\272\321\206\320\270\321\217 \n"
"\320\270\320\275\321\201\321\202\321\200\321\203\320\274\320\265\320\275\321\202\320\260", nullptr));
        button_smesh->setText(QCoreApplication::translate("AntonovCNCClass", "\320\241\320\274\320\265\321\211\320\265\320\275\320\270\320\265 \n"
"\320\275\321\203\320\273\321\217", nullptr));
        button_null3->setText(QString());
        button_null2->setText(QString());
        button_null1->setText(QString());
        button_selectprog->setText(QCoreApplication::translate("AntonovCNCClass", "\320\222\321\213\320\261\320\276\321\200 \n"
"\320\277\321\200\320\276\320\263\321\200\320\260\320\274\320\274\321\213", nullptr));
        label_y_value_final->setText(QCoreApplication::translate("AntonovCNCClass", "y_00", nullptr));
        label_time->setText(QCoreApplication::translate("AntonovCNCClass", "label_time", nullptr));
        label_date->setText(QCoreApplication::translate("AntonovCNCClass", "label_date", nullptr));
        button_numeration->setText(QCoreApplication::translate("AntonovCNCClass", "\320\235\321\203\320\274\320\265\321\200\320\260\321\206\320\270\321\217", nullptr));
        button_smenaekrana->setText(QCoreApplication::translate("AntonovCNCClass", "\320\241\320\274\320\265\320\275\320\260 \n"
"\321\215\320\272\321\200\320\260\320\275\320\260", nullptr));
        button_mmdyum->setText(QCoreApplication::translate("AntonovCNCClass", "\320\234\320\274 / \320\264\321\216\320\271\320\274", nullptr));
        button_changesk->setText(QCoreApplication::translate("AntonovCNCClass", "\320\241\320\274\320\265\320\275\320\260\n"
"\320\270\320\275\321\201\321\202\321\200\321\203\320\274\320\265\320\275\321\202\320\260", nullptr));
        button_priv->setText(QCoreApplication::translate("AntonovCNCClass", "\320\241\320\274\320\265\320\275\320\260\n"
"\321\201\320\270\321\201\321\202\320\265\320\274\321\213\n"
"\320\272\320\276\320\276\321\200\320\264\320\270\320\275\320\260\321\202", nullptr));
        button_ust0pos->setText(QCoreApplication::translate("AntonovCNCClass", "\320\243\321\201\321\202\320\260\320\275\320\276\320\262\320\270\321\202\321\214 \"0\"\n"
"\320\262 \321\202\320\265\320\272\321\203\321\211\320\265\320\271\n"
"\320\277\320\276\320\267\320\270\321\206\320\270\320\270", nullptr));
        button_privyazka->setText(QCoreApplication::translate("AntonovCNCClass", "\320\237\321\200\320\270\320\262\321\217\320\267\320\272\320\260", nullptr));
        button_izmereniya->setText(QCoreApplication::translate("AntonovCNCClass", "\320\230\320\267\320\274\320\265\321\200\320\265\320\275\320\270\321\217...", nullptr));
        label_y_value_current->setText(QCoreApplication::translate("AntonovCNCClass", "y_0", nullptr));
        label_error->setText(QCoreApplication::translate("AntonovCNCClass", "\320\241\321\202\321\200\320\276\320\272\320\260 \320\276\321\210\320\270\320\261\320\276\320\272", nullptr));
        label_chanel->setText(QCoreApplication::translate("AntonovCNCClass", "Chanel 1", nullptr));
        label_sostoyanine->setText(QCoreApplication::translate("AntonovCNCClass", "READY TO START", nullptr));
        label_rejim_isp->setText(QCoreApplication::translate("AntonovCNCClass", "AUTO", nullptr));
        label_z_axis->setText(QCoreApplication::translate("AntonovCNCClass", "Z", nullptr));
        label_z_value_current->setText(QCoreApplication::translate("AntonovCNCClass", "z_0", nullptr));
        label_language->setText(QCoreApplication::translate("AntonovCNCClass", "<html><head/><body><p><span style=\" font-weight:700;\">RU/EN</span></p></body></html>", nullptr));
        label_time_2->setText(QCoreApplication::translate("AntonovCNCClass", "label_time", nullptr));
        label_date_2->setText(QCoreApplication::translate("AntonovCNCClass", "label_date", nullptr));
    } // retranslateUi

};

namespace Ui {
    class AntonovCNCClass: public Ui_AntonovCNCClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_ANTONOVCNC_H
